apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: project-prod
stringData:
    FULLSTACK_DISCORD_WEBHOOK: ENC[AES256_GCM,data:yr4TI6m8FBit9E4nYNEkhg532i6bSxhKbNTAN5TskpimG6L6IAZV9adIVYcbYmcQVTtYSOd1itAw4y9yM9rEGM0=,iv:nBA6gj+THya0zHWnA1d6mcY8kB1nen9z41aBf1Ws5T4=,tag:Bw9qibUR9Ng/EdmRWba5iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b0Y5MkUvU1VObjhOQlZ5
            cVA1bjFaVXpXWkdSeXdpTlVudDZzUk5YblNnCjdBejB6Qm1xN080WXNLaWFEdi8v
            eS81NHRtakFja1BRNENsaVRtek9CdXcKLS0tIGdPSXhDaldYQ1NUZWRsRUZiVDQx
            cm1kZWowWkRLM0VncU1BSzJsUCt5a00KyLSfbkMmDJE9JjYTcoozl/pIzUVzr6it
            5l5/0zKJ1y7cG6GoagXovfunqWBQVOyo605KIF7yYF9f/CtRaGmfFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T12:26:22Z"
    mac: ENC[AES256_GCM,data:6QlQWWriI5PAwh2VBL2pkCbe7vD4tVdW8jX8PjiRX3KVnhzbGXUi+94iDkbMOjiqpw4bWlZGSGEIGs29InsYyPPWzeSkMJigctgG6wuwf7oi6FPRRXS5H2Jo18aZYRis7Nt03EaM5BE/+hp8cr+j4sWwdWpqrOyzrimxsQufkMw=,iv:vg5nH19ZHCBtW2QoO3PPPL2rB6F6VfzrHWz/SWYefSg=,tag:LdblXtIutUBdZYYRm4YUAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
