apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
    name: todo-postgres-password
    namespace: project-prod
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CNpQYFDw2apkXZMX1K5LC12+zFeua3cLYI3Js48sP/4=,iv:D9TsCYl4cmAh6OY623QAGlkojYjfLYmX5z8H3fM/NcE=,tag:aNfC/bWRBlbXECM9svLhkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeVlNNHpWNjhGNTNGdUJz
            UTVYenFscWZqVmtjSDJoR1FBWU5LQWd4NXlnCndnQnRXREsrSzFWcGNHaVZRemN1
            bmVkOXFKb0xKNzNGZFhVTlJmWEhoa3cKLS0tIHgzSXoyR0RaWTlxdHhLVURiK2hu
            QzNtOVlMbHlBbnkrcEFnQWJxa1BwT2cKK1zcJZOUhgsSoHXCFuuWOeNYxlwRjNrV
            AOSgs3GV3v3NLPdY2C0D7fMN82IpByu0boBSMG5FiyHHuWE0Y8LgXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T07:03:42Z"
    mac: ENC[AES256_GCM,data:L+tEAheooPXl6Kub9CJZmIlJispaZCmSVBEgVyCxpcMJVjyYZ3dwVI3Dpdq8i5GJr0sCi33gN/Qp2fa024gXNZGouyiT/tlqtffboptWTUmCAX62iC1OjwhvBLg0wWw7ctgbdAy3X525YByrwyihZrfjpjx0RHHXOjySCFTVwnE=,iv:JRfYvpjoPSY7ITQlTB7n6FIp5q5nKnF5Q+tkhGjvZt0=,tag:zlLDp/U+4UOQhoqwkRJ8pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
