apiVersion: v1
kind: Secret
metadata:
  name: todo-postgres-password
  namespace: project-prod
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:CCXgi7gnX6JA7ZYusrkBWVxUmqocQOdsZV1ZPEA0juc=,iv:8vrcadHVE/tpJ3o5GQSjwrIDM3sVn6RNLvAMfoD9g+o=,tag:78KoY3NZQkZcQIHEe8AFYw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoLzNsRk04M2IybUJWNnkr
        allpdkVZUlBFQ2YwU1dScWR2MmZKcXBkVGhRClJWQ3ZialJyaHE1OVBFS09IRjJN
        SmQzTWJrNkprOVRuYWNiUTAzaGJIOUEKLS0tIEIvR0thY0tyOEI2MVhSNXRXVnVx
        T053d1NsaDZ6VitPcG12VzAxWUlFL3MKreRLmA6QqgQHhl7RorfNqTE0oVg3mm8g
        02ua6EHOVgXqd39Yi1G/xbSHiu4nUWOY2KcHTreF8qcM1eLMMHsNxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T12:16:15Z"
  mac: ENC[AES256_GCM,data:M/hO7tx89HUlb42p4Q6ftpJHK+TQKseoJdlUAkGCU4lmCfh+fbfXiV2Ji7JXFpMa032MjFk7CDHeLq1KVSgyY//RKbJtb1PviWjBs2fakVUh8ZF5BdOGvLs8kz9qDZ1y1Cpbw47vaJjZZRcaZ/QdZpAbPdOGUtoXDA/DGLTrnOA=,iv:ddnsO2/fwaMRsZWWK1PGUouw0FMqQ/CCKxSPOgihEDs=,tag:z6M7dm6zv+zjL5seXB7Otg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
