apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project


resources:
- todo-app/namespace.yaml
- todo-app/deployment.yaml
- todo-app/pvc.yaml
- todo-app/service.yaml
- todo-app/gateway.yaml
- todo-app/route.yaml
- todo-backend/deployment.yaml
- todo-backend/hourly-todo.yaml
- todo-backend/service.yaml
- todo-backend/statefulset.yaml
- todo-backend/cronjob-postgres-backup.yaml
- todo-backend/postgres-config.yaml
- broadcaster/deployment.yaml

images:
- name: BROADCASTER
  newName: vesajo/broadcaster
  newTag: 95c6141c5c0673ef47a252519a250a33b0882aca
- name: TODO_APP
  newName: vesajo/todo-app
  newTag: 95c6141c5c0673ef47a252519a250a33b0882aca
- name: TODO_BACKEND
  newName: vesajo/todo-backend
  newTag: 95c6141c5c0673ef47a252519a250a33b0882aca
