apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vejol/project-config
    path: apps/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
