apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: project-route
  namespace: project
spec:
  parentRefs:
    - name: prod-project-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /todos
      backendRefs:
        - name: prod-todo-backend-svc
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prod-todo-app-svc
          port: 80
