apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  template:
    spec:
      containers:
        - name: project
          env:
            - name: NATS_URL
              value: "nats://prod-my-nats:4222"
