apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging

resources:
- ./../../base

namePrefix: staging-

helmCharts:
- name: nats
  releaseName: my-nats
  repo: oci://registry-1.docker.io/bitnamicharts
  valuesFile: nats_values.yaml
  version: 9.0.28

patches:
- path: patches/postgres-config.yaml
- path: patches/todo-app-deployment.yaml
- path: patches/hourly-todo.yaml
- path: patches/route.yaml
- path: patches/broadcaster-deployment.yaml
- path: patches/todo-backend-deployment.yaml

images:
- name: BROADCASTER
  newName: vesajo/broadcaster
  newTag: 28c113f2a9aff0033e2e089acef5f614c80c1135
- name: TODO_APP
  newName: vesajo/todo-app
  newTag: 28c113f2a9aff0033e2e089acef5f614c80c1135
- name: TODO_BACKEND
  newName: vesajo/todo-backend
  newTag: 28c113f2a9aff0033e2e089acef5f614c80c1135
