apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
- ./../../base

namePrefix: prod-

images:
- name: BROADCASTER
  newName: vesajo/broadcaster
  newTag: 124352a93c0bf7585b045a99abb8809dde36002c
- name: TODO_APP
  newName: vesajo/todo-app
  newTag: 124352a93c0bf7585b045a99abb8809dde36002c
- name: TODO_BACKEND
  newName: vesajo/todo-backend
  newTag: 124352a93c0bf7585b045a99abb8809dde36002c
