apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
  - ./../../base

namePrefix: prod-

helmCharts:
  - name: nats
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 9.0.28
    releaseName: my-nats
    valuesFile: ./../../base/nats_values.yaml

patches:
  - path: patches/postgres-config.yaml
  - path: patches/todo-app-deployment.yaml
  - path: patches/hourly-todo.yaml
  - path: patches/route.yaml

images:
  - name: BROADCASTER
    newName: vesajo/broadcaster
    newTag: 9b6435200bba40e194b838ac661984784f87e3b1
  - name: TODO_APP
    newName: vesajo/todo-app
    newTag: 9b6435200bba40e194b838ac661984784f87e3b1
  - name: TODO_BACKEND
    newName: vesajo/todo-backend
    newTag: 9b6435200bba40e194b838ac661984784f87e3b1
