apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
- ./../../base
- cronjob-postgres-backup.yaml

namePrefix: prod-

helmCharts:
- name: nats
  releaseName: my-nats
  repo: oci://registry-1.docker.io/bitnamicharts
  valuesFile: nats_values.yaml
  version: 9.0.28

patches:
- path: patches/postgres-config.yaml
- path: patches/todo-app-deployment.yaml
- path: patches/hourly-todo.yaml
- path: patches/route.yaml
- path: patches/broadcaster-deployment.yaml
- path: patches/todo-backend-deployment.yaml

images:
- name: BROADCASTER
  newName: vesajo/broadcaster
  newTag: b0285035d1c80e9611bcedc3b973c6af7c207d1d
- name: TODO_APP
  newName: vesajo/todo-app
  newTag: b0285035d1c80e9611bcedc3b973c6af7c207d1d
- name: TODO_BACKEND
  newName: vesajo/todo-backend
  newTag: b0285035d1c80e9611bcedc3b973c6af7c207d1d
