apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          envFrom:
            - secretRef:
                name: discord-webhook
              $patch: delete
