apiVersion: v1
kind: Secret
metadata:
    name: pingpong-postgres-password
    namespace: exercises
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Q0bu0m2J2qs=,iv:JUdWeV4tMH5BTUQvSmgrZ2OuQf+lXAIEScftLgkE3J4=,tag:hSOk2z1wDuX51Aubk35B5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNm8yRXdxQmNUelNUT3Fx
            eVE1aGcxSFlCRTFrS1hlWVowOHJZS1ZTbDNrCnhKSEVBV1Vtem9aUVUwSVZKOHJL
            THhBYmE0cXE2OXNMZDFBWlBOS2RuU00KLS0tIDgrKy9SS20rZlRNOWRNTmxqNzhj
            Z05nZWtCN3pYVk1HUzZtU0s1RmN1UWsKyK2okOtKqsZfnt7E41LFdZ5jHWKo2Fg9
            co/dkqUTHaXPaZxx84cOHhvjosk2+P692xnGasLvpuKdcI7pV+IgYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T07:49:14Z"
    mac: ENC[AES256_GCM,data:sX5fv91beQvXc0rTgeO1bjoKPxq2iu3OEco6GAK02KS2YFf08QEryNCbI9nrYcSrWbE50LIpbFtmLI8zAgH3Ky4FjsM08h9x+TUTY/ahUQ31mz5sDkqZ3KuAc2yrzYJC1+pey1xnhv9WO6XSlb38Hm49o3IlBvW3OEonCOJVUEE=,iv:aUc+RlZUgAdb0gcqssmnKCpJWya/DvgG53k8X7J42ts=,tag:NGFdOrZv4l0zAIkprcYWWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
