apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
    name: discord-webhook
    namespace: project-prod
stringData:
    FULLSTACK_DISCORD_WEBHOOK: ENC[AES256_GCM,data:ST8ZQ8ZvfNXBFt7cOOkPnnpdPceUf3oXAGjndPA04zAwxd3lVSL3FSmFjGwBo6WEI4MJjVFLUQgHv/PQ8kVxFE4=,iv:Gte39m6x5joG3YNf9W96ciys3QnyhpI0NJAfFiNXyNw=,tag:dIwmrAJKgd/1SLiCfmSqRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOFY1VkcxSTM2OUp6NzhM
            alZqNTh2WnNqVEl4TUM3ZHRVbEtxVTUzL2prCmtJWE9xeVNtMjIvQ3R4ZTlWZzA2
            UXB2dWlyMEdpQ294cHNSb01wcVdBTzAKLS0tIDcvenlLVU9YWmZ0ZGZZK0REUkha
            WXFwTWRhTDdCNGNYdFo3bE5jZjFVbEUKsQZ+Nh52grXul2A20s1uDhHXxadhMvi1
            0sR9qajcq41opq5KVwDRMTwgjNhgZ9Ww2qUp/9UbAYeSuTV6DO54Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T07:03:42Z"
    mac: ENC[AES256_GCM,data:7OVIzoxAqcLJxNWwiUWLY9eMxTtO7YNieP9bs0rV1rv2R/60oeeOXUBxv/8P2L09TrHer53W9p21K+nn5mIxJV6sbfXfVHC7HT4DontndBECzeQBB1Pntk4NSdAXb46FixAK2VUL+VRQYaKGgQT9W1jbqNao9sNBGoldohg8afQ=,iv:Sy/2U+ncQtt4VjJaHPLPUxCO/AO16XiMl6iISwmhBo0=,tag:pi5lqhSyYh2gUyKVyF88nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
