apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vejol/kubernetes-submissions
    path: chapter5/project/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: project-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
