apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts
      chart: nats
      targetRevision: 9.0.28
      helm:
        releaseName: my-nats
        valueFiles:
          - $values/chapter5/project/nats_values.yaml
    - repoURL: https://github.com/vejol/kubernetes-submissions
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: project-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
