apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
    name: discord-webhook
    namespace: project-staging
stringData:
    FULLSTACK_DISCORD_WEBHOOK: ENC[AES256_GCM,data:pXgtt5pABfYI9nxsIREE2bMgBB+BS4pKdNsS4FJ72KeGk2WeqF+1AvRSu26CMdef1arBEpIlaaCkisSBEva5hYI=,iv:8h5oFvtY9jwC9thdvhO/kYRNppTySsuywp8oYDVfcas=,tag:uZOi9ZvcfXt88xuNCz1MSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMG95aXVEZi9LdlhrTTBu
            MFFURzdTNnh5WFg1WEgwemtTbWdRK3BuZURNCjN5SzRjTW5QcmZ0UUN2aXVLUkli
            ZEJhTlBZd2tpenNGZkw5eWQxdUpyNVEKLS0tIDBsVE0zTDRNZ29hRzkvT2hsV0J6
            ckxvZlBMRGYweTdaQUg3dmxGVmR2MncKMsyHt69UlN6u2P8SqWODSUAGYn57NbTr
            xMjwFZwqWWR2I+4heUMecQME5fNqq1ylPMyh+U49AtjzQyMtTv/zOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T07:03:42Z"
    mac: ENC[AES256_GCM,data:F7WEpc4PEsJwQr8dPy184zxsAhKNw1Obi/PnfaANI6QogdKlC0VWAUVkL6kWFEQfp1BKFr/ahbxcdnrMO31oApbXVi86qqbLFa2181qxn2Y6iifodVjExChuuUX/v6YYs7tIDiYiR59BWf5hsklRP3QWe76kjnIEddH9Rj7nA9A=,iv:nsD0mistUPmzB38Rt9q5EX+XvBJaVFAwjIgy51MjpD4=,tag:L81z26eEFevMXb/CRs6AIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
