apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: project-staging
stringData:
    FULLSTACK_DISCORD_WEBHOOK: ENC[AES256_GCM,data:F+ofB6f7Q174BMbGlCLtJmcXFhDk8X75vtCh3mVikbd5trM6kLYb8RFMjdz2MM/jYfu1JAJYMElyvajflzdfbtM=,iv:jCkRKKQ5+FOuNpC7CM7NrU5+QMSF/p7X5JPcUxHlTpY=,tag:tkxcjbNjqL9UPgnrCBI27g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNTE1WnAvdG9IaTYxMnJE
            NHZqaDgvUDNSOHNuaysyRGszT3ZnZGtTeGtzCmEzMjVXZ2lyRVdJL1pPWmdrSkwv
            OXV1cTRrQnVBK2JCNFJVcDFZcktydTgKLS0tIDYzbVcwMlVROUlKOWwxckZPL2Fv
            bFRyY2k5bk9IZjdOalVyb3VKdVZUdmsKQ+i2lmOdDLKAzF/AhDYCP1OiZM76bJcT
            6It64XCbQPD5E7siNqk/JTjInRnJnqBXcMq3nyhhhjrDtG+p+WGZ1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T12:26:37Z"
    mac: ENC[AES256_GCM,data:e7c8Ch0IBZTrJV0RC0cmCXLxiddcOSyUMotluzJYSA/TzFdU7x+DXRw+fyMnejLWhd2Kfk/8vEINp5ILyyFzOgTcWSqvN3ZlYzCu09AXJIHowNeye8RU/tU8LjmIBjCCXPyOW1pJyv7p6/X9gCoGRcgWBKnYaJcNyVg24TMm728=,iv:4UgMmmDY+qEcRwirzWjmZQc+5pyB6PopWlvetMPLb34=,tag:sNqEcJQuwkBQ5g/e6hnMBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
