apiVersion: v1
kind: Secret
metadata:
    name: todo-postgres-password
    namespace: project-staging
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:31x8qKnwnF0aYNF9IEYNZEwFPMadkh9kKw==,iv:XcdXCfbhcE5qMxuZnQmlHaDINRPBoce9EfMKa0h+Ivs=,tag:b9HSsS+b5qZRGy+1D5jZKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVHhLR0FaUzZQck9DQXRD
            SzdNclJZRjZYc3RYNDVuVjExdFkxdU5ydFF3CndkWXlwRXI5VDFMR3NzOFoyMGJX
            YVN1aEJicXJPcjk2eXcxTzZiUElaNUEKLS0tIFFpdzE2cWEwbjFHVU9kWmlRN1di
            bXo3cGJ6ZG9FMzE3RG1HU01ZU0U5dU0KC929DdN+wBoRcMaFBHmCH5y0669AfRw7
            PVBpU/o9+p2I+jXNiYD0rdmB8ijAlRCnz7jEy57KC5XWmdjoba/wEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T12:20:22Z"
    mac: ENC[AES256_GCM,data:iwb10y6Vm4HPn/1+ufavD5uB5V9OdpwawQr8c/i6WOfqPCHS2iDL5GcrGeHR1PqYH8OCtKMAiH08gdl3+VxgT6J1Qo0i3itGn3vHAU/4VIRNknr6MdhUxuXsULRIrTVGoSac4k5LOcHeFl9s/4+GfceIsZqAbG4qgogutgpO7fs=,iv:D0LvOsX1J82hFBp/0tv3kO5NqozMpbEf+ZMqbqUvg0c=,tag:9zqKjFCKFze9+ufZubEpaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
