apiVersion: v1
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
    name: todo-postgres-password
    namespace: project-staging
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LLeOi5YpnsGmUUUav7lhP/Glp2XJquPjCQ==,iv:V4y0YqjCkOWs77Pqnkn5ZpvygFPRNn7XUHV8X/5J6go=,tag:ubP3+UzRIKrQUUVzu00+RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w6csmk7r86jcprkkkr6chw6m9q8vugd9zvy78zcpvfp8repq4fns36l9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK3Z2clZOQkh3Z1dGbkdJ
            RnlCZTVjdmNoNU9UZTB1THkybXY0OXZyREdnClVSR3k3b254U0plZnVqYkI5YWFG
            YmFGNXJGdjlYMk9uL01ma1VTU28zQVkKLS0tIGQramhTbHlub2ZYQm9sRkFTaVJn
            VFQ2eXBtYWVKUFd2TjdTWXhpQmhkaWMK8lGvnRz8/mAyBipX9uv3y0FztvA43cqt
            Ui9U6H9FhvhzuavAjah9jen4OjVxrzCGpSei2bQtT9swTJ/WUIdWhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T07:03:42Z"
    mac: ENC[AES256_GCM,data:hr7fwoXO2vRDXh4ssikcHHbqk4C+rWuUcsksfYk6NLTs+RzAny/MCuqbSDi5KZWipeAyiGbmdqKmsnEl60mZB4eiZirC2soZgLXDHsfkCVg+umUoOWeYRnv9u7XZcSEkxE1W4qzhrQ+C2U6TIvEHH5vMJdkvm1h4+bJLhf8Ykaw=,iv:vZM9YcUWna7PCVtcK+kfJiHpgnlLY0PtGwvcB+FF0mY=,tag:hs2vK3ZBYA1ZymsNOEVTeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
