apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging

resources:
- ./../../base

namePrefix: staging-

patches:
- path: patches/postgres-config.yaml
- path: patches/todo-app-deployment.yaml

images:
- name: BROADCASTER
  newName: vesajo/broadcaster
  newTag: cdc778a08a98731a59367c52a849e8c0460710d7
- name: TODO_APP
  newName: vesajo/todo-app
  newTag: cdc778a08a98731a59367c52a849e8c0460710d7
- name: TODO_BACKEND
  newName: vesajo/todo-backend
  newTag: cdc778a08a98731a59367c52a849e8c0460710d7
