apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging

resources:
- ./../../base

namePrefix: staging-

patches:
- path: patches/postgres-config.yaml
- path: patches/todo-app-deployment.yaml
- path: patches/hourly-todo.yaml
- path: patches/route.yaml

images:
- name: BROADCASTER
  newName: vesajo/broadcaster
  newTag: 25095f26d280bdf1b4002fe94078407189c379d0
- name: TODO_APP
  newName: vesajo/todo-app
  newTag: 25095f26d280bdf1b4002fe94078407189c379d0
- name: TODO_BACKEND
  newName: vesajo/todo-backend
  newTag: 25095f26d280bdf1b4002fe94078407189c379d0
