name: Release pingpong

on:
  push:
    branches: [ main ]
    paths:
      - "chapter5/pingpong_logoutput/**"
  workflow_dispatch:

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish ping-pong
        run: |-
          docker build --tag "${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:$GITHUB_SHA" \
            ./chapter5/pingpong_logoutput/ping_pong
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:$GITHUB_SHA"

      - name: Build and publish hash-generator
        run: |-
          docker build --tag "${{ secrets.DOCKERHUB_USERNAME }}/hash-generator:$GITHUB_SHA" \
            ./chapter5/pingpong_logoutput/log_output/hash_generator
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/hash-generator:$GITHUB_SHA"

      - name: Build and publish hash-outputter
        run: |-
          docker build --tag "${{ secrets.DOCKERHUB_USERNAME }}/hash-outputter:$GITHUB_SHA" \
            ./chapter5/pingpong_logoutput/log_output/hash_outputter
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/hash-outputter:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3
        with:
          kustomize-version: "5.8.1"

      - name: Use right images
        working-directory: ./chapter5/pingpong_logoutput
        run: |-
          kustomize edit set image PING_PONG=${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:$GITHUB_SHA
          kustomize edit set image HASH_GENERATOR=${{ secrets.DOCKERHUB_USERNAME }}/hash-generator:$GITHUB_SHA
          kustomize edit set image HASH_OUTPUTTER=${{ secrets.DOCKERHUB_USERNAME }}/hash-outputter:$GITHUB_SHA

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v10
        with:
          add: "kustomization.yaml"
          message: New version released ${{ github.sha }}
